spring:
  profiles:
    default: local
  jpa:
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}

jwt:
  access-token-expiration-seconds: ${JWT_ACCESS_TOKEN_EXPIRATION_SECONDS:3600}
  token-type: ${JWT_TOKEN_TYPE:Bearer}
