CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    industry VARCHAR(100),
    website_url VARCHAR(500),
    memo TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_companies_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    job_title VARCHAR(255) NOT NULL,
    application_route VARCHAR(100),
    status VARCHAR(50) NOT NULL,
    applied_at DATE,
    result_date DATE,
    offer_deadline DATE,
    priority INTEGER NOT NULL,
    is_archived BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_applications_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_applications_company FOREIGN KEY (company_id) REFERENCES companies (id)
);

CREATE TABLE stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    stage_order INTEGER NOT NULL,
    stage_type VARCHAR(50) NOT NULL,
    stage_name VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL,
    scheduled_at TIMESTAMP,
    completed_at TIMESTAMP,
    result_date DATE,
    memo TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_stages_application FOREIGN KEY (application_id) REFERENCES applications (id)
);

CREATE TABLE schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    stage_id BIGINT,
    schedule_type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP,
    location VARCHAR(255),
    is_all_day BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_schedules_application FOREIGN KEY (application_id) REFERENCES applications (id),
    CONSTRAINT fk_schedules_stage FOREIGN KEY (stage_id) REFERENCES stages (id)
);

CREATE TABLE notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    title VARCHAR(100),
    note_type VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_notes_application FOREIGN KEY (application_id) REFERENCES applications (id)
);

CREATE TABLE application_status_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    from_status VARCHAR(50),
    to_status VARCHAR(50) NOT NULL,
    changed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_application_status_histories_application
        FOREIGN KEY (application_id) REFERENCES applications (id)
);

CREATE TABLE stage_status_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage_id BIGINT NOT NULL,
    from_status VARCHAR(50),
    to_status VARCHAR(50) NOT NULL,
    changed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_stage_status_histories_stage FOREIGN KEY (stage_id) REFERENCES stages (id)
);

CREATE INDEX idx_companies_user_id ON companies (user_id);
CREATE INDEX idx_applications_user_id ON applications (user_id);
CREATE INDEX idx_applications_company_id ON applications (company_id);
CREATE INDEX idx_stages_application_id ON stages (application_id);
CREATE INDEX idx_schedules_application_id ON schedules (application_id);
CREATE INDEX idx_schedules_stage_id ON schedules (stage_id);
CREATE INDEX idx_notes_application_id ON notes (application_id);
CREATE INDEX idx_application_status_histories_application_id
    ON application_status_histories (application_id);
CREATE INDEX idx_stage_status_histories_stage_id ON stage_status_histories (stage_id);
